/** Countries for mobile sign-in: ISO code, dialling code and names. Iran is the default. */
export type Country = { iso: string; dial: string; fa: string; en: string };

export const DEFAULT_COUNTRY = 'IR';

export const COUNTRIES: Country[] = [
  { iso: 'IR', dial: '98', fa: 'ایران', en: 'Iran' },
  { iso: 'AF', dial: '93', fa: 'افغانستان', en: 'Afghanistan' },
  { iso: 'TJ', dial: '992', fa: 'تاجیکستان', en: 'Tajikistan' },
  { iso: 'TR', dial: '90', fa: 'ترکیه', en: 'Turkey' },
  { iso: 'AE', dial: '971', fa: 'امارات', en: 'United Arab Emirates' },
  { iso: 'IQ', dial: '964', fa: 'عراق', en: 'Iraq' },
  { iso: 'DE', dial: '49', fa: 'آلمان', en: 'Germany' },
  { iso: 'GB', dial: '44', fa: 'انگلستان', en: 'United Kingdom' },
  { iso: 'US', dial: '1', fa: 'آمریکا', en: 'United States' },
  { iso: 'CA', dial: '1', fa: 'کانادا', en: 'Canada' },
  { iso: 'AL', dial: '355', fa: 'آلبانی', en: 'Albania' },
  { iso: 'DZ', dial: '213', fa: 'الجزایر', en: 'Algeria' },
  { iso: 'AD', dial: '376', fa: 'آندورا', en: 'Andorra' },
  { iso: 'AO', dial: '244', fa: 'آنگولا', en: 'Angola' },
  { iso: 'AR', dial: '54', fa: 'آرژانتین', en: 'Argentina' },
  { iso: 'AM', dial: '374', fa: 'ارمنستان', en: 'Armenia' },
  { iso: 'AU', dial: '61', fa: 'استرالیا', en: 'Australia' },
  { iso: 'AT', dial: '43', fa: 'اتریش', en: 'Austria' },
  { iso: 'AZ', dial: '994', fa: 'آذربایجان', en: 'Azerbaijan' },
  { iso: 'BH', dial: '973', fa: 'بحرین', en: 'Bahrain' },
  { iso: 'BD', dial: '880', fa: 'بنگلادش', en: 'Bangladesh' },
  { iso: 'BY', dial: '375', fa: 'بلاروس', en: 'Belarus' },
  { iso: 'BE', dial: '32', fa: 'بلژیک', en: 'Belgium' },
  { iso: 'BO', dial: '591', fa: 'بولیوی', en: 'Bolivia' },
  { iso: 'BA', dial: '387', fa: 'بوسنی و هرزگوین', en: 'Bosnia and Herzegovina' },
  { iso: 'BR', dial: '55', fa: 'برزیل', en: 'Brazil' },
  { iso: 'BG', dial: '359', fa: 'بلغارستان', en: 'Bulgaria' },
  { iso: 'KH', dial: '855', fa: 'کامبوج', en: 'Cambodia' },
  { iso: 'CM', dial: '237', fa: 'کامرون', en: 'Cameroon' },
  { iso: 'CL', dial: '56', fa: 'شیلی', en: 'Chile' },
  { iso: 'CN', dial: '86', fa: 'چین', en: 'China' },
  { iso: 'CO', dial: '57', fa: 'کلمبیا', en: 'Colombia' },
  { iso: 'CR', dial: '506', fa: 'کاستاریکا', en: 'Costa Rica' },
  { iso: 'HR', dial: '385', fa: 'کرواسی', en: 'Croatia' },
  { iso: 'CU', dial: '53', fa: 'کوبا', en: 'Cuba' },
  { iso: 'CY', dial: '357', fa: 'قبرس', en: 'Cyprus' },
  { iso: 'CZ', dial: '420', fa: 'چک', en: 'Czechia' },
  { iso: 'DK', dial: '45', fa: 'دانمارک', en: 'Denmark' },
  { iso: 'DO', dial: '1', fa: 'جمهوری دومینیکن', en: 'Dominican Republic' },
  { iso: 'EC', dial: '593', fa: 'اکوادور', en: 'Ecuador' },
  { iso: 'EG', dial: '20', fa: 'مصر', en: 'Egypt' },
  { iso: 'EE', dial: '372', fa: 'استونی', en: 'Estonia' },
  { iso: 'ET', dial: '251', fa: 'اتیوپی', en: 'Ethiopia' },
  { iso: 'FI', dial: '358', fa: 'فنلاند', en: 'Finland' },
  { iso: 'FR', dial: '33', fa: 'فرانسه', en: 'France' },
  { iso: 'GE', dial: '995', fa: 'گرجستان', en: 'Georgia' },
  { iso: 'GH', dial: '233', fa: 'غنا', en: 'Ghana' },
  { iso: 'GR', dial: '30', fa: 'یونان', en: 'Greece' },
  { iso: 'GT', dial: '502', fa: 'گواتمالا', en: 'Guatemala' },
  { iso: 'HK', dial: '852', fa: 'هنگ‌کنگ', en: 'Hong Kong' },
  { iso: 'HU', dial: '36', fa: 'مجارستان', en: 'Hungary' },
  { iso: 'IS', dial: '354', fa: 'ایسلند', en: 'Iceland' },
  { iso: 'IN', dial: '91', fa: 'هند', en: 'India' },
  { iso: 'ID', dial: '62', fa: 'اندونزی', en: 'Indonesia' },
  { iso: 'IE', dial: '353', fa: 'ایرلند', en: 'Ireland' },
  { iso: 'IT', dial: '39', fa: 'ایتالیا', en: 'Italy' },
  { iso: 'JP', dial: '81', fa: 'ژاپن', en: 'Japan' },
  { iso: 'JO', dial: '962', fa: 'اردن', en: 'Jordan' },
  { iso: 'KZ', dial: '7', fa: 'قزاقستان', en: 'Kazakhstan' },
  { iso: 'KE', dial: '254', fa: 'کنیا', en: 'Kenya' },
  { iso: 'KW', dial: '965', fa: 'کویت', en: 'Kuwait' },
  { iso: 'KG', dial: '996', fa: 'قرقیزستان', en: 'Kyrgyzstan' },
  { iso: 'LV', dial: '371', fa: 'لتونی', en: 'Latvia' },
  { iso: 'LB', dial: '961', fa: 'لبنان', en: 'Lebanon' },
  { iso: 'LY', dial: '218', fa: 'لیبی', en: 'Libya' },
  { iso: 'LT', dial: '370', fa: 'لیتوانی', en: 'Lithuania' },
  { iso: 'LU', dial: '352', fa: 'لوکزامبورگ', en: 'Luxembourg' },
  { iso: 'MY', dial: '60', fa: 'مالزی', en: 'Malaysia' },
  { iso: 'MV', dial: '960', fa: 'مالدیو', en: 'Maldives' },
  { iso: 'MT', dial: '356', fa: 'مالت', en: 'Malta' },
  { iso: 'MX', dial: '52', fa: 'مکزیک', en: 'Mexico' },
  { iso: 'MD', dial: '373', fa: 'مولداوی', en: 'Moldova' },
  { iso: 'MC', dial: '377', fa: 'موناکو', en: 'Monaco' },
  { iso: 'MN', dial: '976', fa: 'مغولستان', en: 'Mongolia' },
  { iso: 'ME', dial: '382', fa: 'مونته‌نگرو', en: 'Montenegro' },
  { iso: 'MA', dial: '212', fa: 'مراکش', en: 'Morocco' },
  { iso: 'NL', dial: '31', fa: 'هلند', en: 'Netherlands' },
  { iso: 'NZ', dial: '64', fa: 'نیوزیلند', en: 'New Zealand' },
  { iso: 'NG', dial: '234', fa: 'نیجریه', en: 'Nigeria' },
  { iso: 'MK', dial: '389', fa: 'مقدونیه‌ی شمالی', en: 'North Macedonia' },
  { iso: 'NO', dial: '47', fa: 'نروژ', en: 'Norway' },
  { iso: 'OM', dial: '968', fa: 'عمان', en: 'Oman' },
  { iso: 'PK', dial: '92', fa: 'پاکستان', en: 'Pakistan' },
  { iso: 'PA', dial: '507', fa: 'پاناما', en: 'Panama' },
  { iso: 'PY', dial: '595', fa: 'پاراگوئه', en: 'Paraguay' },
  { iso: 'PE', dial: '51', fa: 'پرو', en: 'Peru' },
  { iso: 'PH', dial: '63', fa: 'فیلیپین', en: 'Philippines' },
  { iso: 'PL', dial: '48', fa: 'لهستان', en: 'Poland' },
  { iso: 'PT', dial: '351', fa: 'پرتغال', en: 'Portugal' },
  { iso: 'QA', dial: '974', fa: 'قطر', en: 'Qatar' },
  { iso: 'RO', dial: '40', fa: 'رومانی', en: 'Romania' },
  { iso: 'RU', dial: '7', fa: 'روسیه', en: 'Russia' },
  { iso: 'SA', dial: '966', fa: 'عربستان سعودی', en: 'Saudi Arabia' },
  { iso: 'RS', dial: '381', fa: 'صربستان', en: 'Serbia' },
  { iso: 'SG', dial: '65', fa: 'سنگاپور', en: 'Singapore' },
  { iso: 'SK', dial: '421', fa: 'اسلواکی', en: 'Slovakia' },
  { iso: 'SI', dial: '386', fa: 'اسلوونی', en: 'Slovenia' },
  { iso: 'ZA', dial: '27', fa: 'آفریقای جنوبی', en: 'South Africa' },
  { iso: 'KR', dial: '82', fa: 'کره‌ی جنوبی', en: 'South Korea' },
  { iso: 'ES', dial: '34', fa: 'اسپانیا', en: 'Spain' },
  { iso: 'LK', dial: '94', fa: 'سریلانکا', en: 'Sri Lanka' },
  { iso: 'SE', dial: '46', fa: 'سوئد', en: 'Sweden' },
  { iso: 'CH', dial: '41', fa: 'سوئیس', en: 'Switzerland' },
  { iso: 'SY', dial: '963', fa: 'سوریه', en: 'Syria' },
  { iso: 'TW', dial: '886', fa: 'تایوان', en: 'Taiwan' },
  { iso: 'TZ', dial: '255', fa: 'تانزانیا', en: 'Tanzania' },
  { iso: 'TH', dial: '66', fa: 'تایلند', en: 'Thailand' },
  { iso: 'TN', dial: '216', fa: 'تونس', en: 'Tunisia' },
  { iso: 'TM', dial: '993', fa: 'ترکمنستان', en: 'Turkmenistan' },
  { iso: 'UG', dial: '256', fa: 'اوگاندا', en: 'Uganda' },
  { iso: 'UA', dial: '380', fa: 'اوکراین', en: 'Ukraine' },
  { iso: 'UY', dial: '598', fa: 'اروگوئه', en: 'Uruguay' },
  { iso: 'UZ', dial: '998', fa: 'ازبکستان', en: 'Uzbekistan' },
  { iso: 'VE', dial: '58', fa: 'ونزوئلا', en: 'Venezuela' },
  { iso: 'VN', dial: '84', fa: 'ویتنام', en: 'Vietnam' },
  { iso: 'YE', dial: '967', fa: 'یمن', en: 'Yemen' },
];

export function findCountry(iso: string): Country {
  return COUNTRIES.find((c) => c.iso === iso) ?? COUNTRIES[0];
}

/** The flag emoji of an ISO code (two regional-indicator letters). */
export function flagOf(iso: string): string {
  return String.fromCodePoint(...[...iso.toUpperCase()].map((ch) => 0x1f1e6 + ch.charCodeAt(0) - 65));
}
