// Generated by scripts/i18n-index.ts from the files in this folder; don't edit by hand.
import type { Overlay } from '..';

import courses from './courses.json';

export const EN_COURSES: Record<string, Overlay> = courses;

export const EN_UNITS: Record<string, Overlay> = {
};
