import { BREAKOUT, DOWNTREND, RESISTANCE_REJECTION, SUPPORT_BOUNCES, UPTREND, level } from '../../charts';
import type { Unit } from '../../types';

export const u1: Unit = {
  id: 'trend',
  title: 'روند و سطوح',
  color: '#A78BFA',
  edge: '#7556D9',
  ink: '#1E1240',
  lessons: [
    {
      id: 'tr-1',
      title: 'روند چیه؟',
      steps: [
        {
          type: 'learn',
          title: 'روند صعودی و نزولی',
          body: '**روند صعودی** یعنی قیمت **سقف‌ها و کف‌های بالاتر** می‌سازه. **روند نزولی** یعنی **سقف‌ها و کف‌های پایین‌تر**. اگه قیمت بین دو سطح بالا و پایین بره، بازار **رِنج (خنثی)** هست.',
          visual: { kind: 'chart', chart: { candles: UPTREND, ma: 4 }, symbol: 'روند صعودی' },
        },
        {
          type: 'learn',
          title: 'با روند معامله کن',
          body: 'یه جمله‌ی معروف بین تریدرها: **«روند دوست توئه»**. تازه‌کارها بهتره **هم‌جهت با روند** معامله کنن، نه خلافش.',
          tip: 'توی روند صعودی دنبال خرید بگرد، توی روند نزولی دنبال فروش.',
        },
        {
          type: 'chart',
          prompt: 'روند این نمودار چیه؟',
          chart: { candles: UPTREND },
          symbol: 'EUR/USD · 4H',
          options: [{ label: 'صعودی' }, { label: 'نزولی' }, { label: 'خنثی (رنج)' }],
          answer: 0,
          explanation: 'هر کف از کف قبلی بالاتره و هر سقف از سقف قبلی؛ این یعنی روند صعودی.',
        },
        {
          type: 'chart',
          prompt: 'این یکی چی؟',
          chart: { candles: DOWNTREND },
          symbol: 'BTC/USDT · 1D',
          options: [{ label: 'نزولی' }, { label: 'صعودی' }, { label: 'خنثی (رنج)' }],
          answer: 0,
          explanation: 'سقف‌ها و کف‌ها مدام پایین‌تر می‌رن؛ روند نزولیه.',
        },
        {
          type: 'truefalse',
          statement: 'توی روند صعودی، کف‌های جدید پایین‌تر از کف‌های قبلی ساخته می‌شن.',
          topic: 'روند صعودی',
          answer: false,
          explanation: 'توی روند صعودی کف‌ها بالاتر می‌رن. اگه کف جدید پایین‌تر بشه، روند داره ضعیف می‌شه.',
        },
        {
          type: 'choice',
          prompt: 'توی یه روند نزولی قوی، کدوم کار منطقی‌تره؟',
          options: ['دنبال فرصت فروش گشتن', 'هر بار که قیمت افت کرد خریدن', 'برداشتن حد ضرر', 'زیاد کردن اهرم'],
          answer: 0,
          explanation: 'هم‌جهت با روند معامله کن. خرید توی روند نزولی مثل گرفتن چاقوی در حال سقوطه.',
        },
      ],
    },
    {
      id: 'tr-2',
      title: 'حمایت و مقاومت',
      steps: [
        {
          type: 'learn',
          title: 'حمایت',
          body: '**حمایت** سطحیه که قیمت چند بار بهش رسیده و **برگشته بالا**؛ انگار یه کف محکم زیر قیمته. اونجا خریدارها فعال می‌شن.',
          visual: { kind: 'chart', chart: { candles: SUPPORT_BOUNCES, lines: [level.support(1.08)] }, symbol: 'حمایت' },
        },
        {
          type: 'learn',
          title: 'مقاومت',
          body: '**مقاومت** سطحیه که قیمت چند بار بهش خورده و **برگشته پایین**؛ مثل یه سقف. اونجا فروشنده‌ها فعال می‌شن. هر چی یه سطح بیشتر تست بشه، مهم‌تره.',
          visual: {
            kind: 'chart',
            chart: { candles: RESISTANCE_REJECTION, lines: [level.resistance(1.092)] },
            symbol: 'مقاومت',
          },
        },
        {
          type: 'chart',
          prompt: 'خط‌چین زرد چه سطحیه؟',
          chart: { candles: SUPPORT_BOUNCES, lines: [level.unknown(1.08)] },
          symbol: 'EUR/USD · 1H',
          options: [{ label: 'حمایت' }, { label: 'مقاومت' }, { label: 'حد سود' }, { label: 'اسپرد' }],
          answer: 0,
          explanation: 'قیمت دو بار به این سطح رسیده و برگشته بالا؛ پس یه سطح حمایته.',
        },
        {
          type: 'predict',
          prompt: 'قیمت به مقاومت رسیده؛ چی کار می‌کنی؟',
          chart: { candles: RESISTANCE_REJECTION, ghost: true, lines: [level.resistance(1.092, '1.0920')] },
          symbol: 'EUR/USD · 4H',
          trend: 'up',
          answer: 'sell',
          explanation: 'قیمت دو بار به مقاومت ۱٫۰۹۲۰ خورده و برگشته، و کندل آخر یه ستاره‌ی دنباله‌داره؛ یعنی خریدارها دیگه زور ندارن. خرید درست زیر مقاومت ریسک بالایی داره.',
        },
        {
          type: 'truefalse',
          statement: 'مقاومت سطحیه که قیمت معمولاً از اونجا برمی‌گرده پایین.',
          topic: 'مقاومت · Resistance',
          answer: true,
          explanation: 'فروشنده‌ها توی سطح مقاومت فعال می‌شن و جلوی بالا رفتن قیمت رو می‌گیرن.',
        },
        {
          type: 'match',
          pairs: [
            { term: 'حمایت', sub: 'Support', meaning: 'کفی که قیمت ازش برمی‌گرده بالا' },
            { term: 'مقاومت', sub: 'Resistance', meaning: 'سقفی که قیمت ازش برمی‌گرده پایین' },
            { term: 'روند صعودی', sub: 'Uptrend', meaning: 'سقف‌ها و کف‌های بالاتر' },
            { term: 'رنج', sub: 'Range', meaning: 'حرکت قیمت بین دو سطح' },
          ],
        },
      ],
    },
    {
      id: 'tr-3',
      title: 'شکست و تغییر نقش',
      steps: [
        {
          type: 'learn',
          title: 'شکست (Breakout)',
          body: 'وقتی قیمت با یه کندل قوی **بالای مقاومت بسته بشه**، می‌گیم مقاومت **شکسته شده**. شکست معتبر معمولاً با **حجم معاملات بالا** همراهه.',
          visual: { kind: 'chart', chart: { candles: BREAKOUT, lines: [level.resistance(1.085)], highlight: BREAKOUT.length - 1 }, symbol: 'شکست مقاومت' },
        },
        {
          type: 'learn',
          title: 'تغییر نقش',
          body: 'بعد از شکست، اغلب **مقاومت قبلی نقش حمایت** رو بازی می‌کنه (و برعکس). به برگشت قیمت به سطح شکسته‌شده **پولبک** می‌گن.',
          tip: 'پولبک به سطح شکسته‌شده، معمولاً فرصت ورود کم‌ریسک‌تریه تا دنبال کردن کندل شکست.',
        },
        {
          type: 'fill',
          sentence: 'وقتی قیمت ___ رو به سمت بالا می‌شکنه، اون سطح ممکنه به ___ تبدیل بشه.',
          answers: ['مقاومت', 'حمایت'],
          distractors: ['روند', 'اسپرد'],
          explanation: 'سقف قبلی بعد از شکست، می‌تونه کف جدید باشه.',
        },
        {
          type: 'chart',
          prompt: 'توی کندل آخر چه اتفاقی افتاده؟',
          chart: { candles: BREAKOUT, lines: [level.resistance(1.085)], highlight: BREAKOUT.length - 1 },
          symbol: 'EUR/USD · 1H',
          options: [{ label: 'شکست مقاومت' }, { label: 'برگشت از مقاومت' }, { label: 'شکست حمایت' }, { label: 'بازار خنثی شده' }],
          answer: 0,
          explanation: 'کندل آخر با بدنه‌ی قوی بالای مقاومت بسته شده؛ یعنی مقاومت شکسته شده.',
        },
        {
          type: 'truefalse',
          statement: 'به برگشت قیمت به سطح شکسته‌شده، پولبک می‌گن.',
          topic: 'پولبک · Pullback',
          answer: true,
          explanation: 'بعد از شکست، قیمت اغلب برمی‌گرده و سطح رو دوباره تست می‌کنه؛ به این می‌گن پولبک.',
        },
        {
          type: 'choice',
          prompt: 'کدوم نشونه، شکست رو معتبرتر می‌کنه؟',
          options: [
            'بسته شدن قوی بالای سطح با حجم بالا',
            'یه سایه‌ی کوتاه بالای سطح و برگشت',
            'حجم معاملات خیلی کم',
            'شکست موقع تعطیلی بازار',
          ],
          answer: 0,
          explanation: 'بسته شدن بدنه بالای سطح، همراه با حجم بالا، یعنی خریدارهای واقعی پشت حرکتن.',
        },
      ],
    },
  ],
};
