import {
  BEAR_ENGULF_AFTER_UPTREND,
  BULL_ENGULF_AFTER_DOWNTREND,
  HAMMER_AFTER_DOWNTREND,
  LAST_BEARISH,
  PATTERN_OPTIONS as P,
  SHOOTING_STAR_AFTER_UPTREND,
} from '../../charts';
import type { Unit } from '../../types';

export const u1: Unit = {
  id: 'candles',
  title: 'خوندن نمودار شمعی',
  color: '#FF8A7A',
  edge: '#D65A4A',
  ink: '#3A0E08',
  lessons: [
    {
      id: 'cd-1',
      title: 'آناتومی کندل',
      steps: [
        {
          type: 'learn',
          title: 'یه کندل چی می‌گه؟',
          body: 'هر **کندل** حرکت قیمت رو توی یه بازه‌ی زمانی نشون می‌ده (مثلاً ۱ ساعت). چهار قیمت داره: **باز شدن (Open)**، **بسته شدن (Close)**، **سقف (High)** و **کف (Low)**.',
          visual: { kind: 'anatomy' },
        },
        {
          type: 'learn',
          title: 'بدنه و سایه',
          body: '**بدنه** فاصله‌ی باز و بسته شدنه و **سایه‌ها** سقف و کف قیمت رو نشون می‌دن. کندل **سبز (صعودی)** یعنی قیمت بالاتر از باز شدن بسته شده و کندل **قرمز (نزولی)** یعنی پایین‌تر.',
          visual: { kind: 'glyphs', items: [{ glyph: 'bullish', label: 'صعودی' }, { glyph: 'bearish', label: 'نزولی' }] },
        },
        {
          type: 'choice',
          prompt: 'توی کندل صعودی (سبز)، بالای بدنه نشون‌دهنده‌ی چه قیمتیه؟',
          options: ['قیمت بسته شدن', 'قیمت باز شدن', 'سقف قیمت', 'کف قیمت'],
          answer: 0,
          explanation: 'توی کندل صعودی قیمت بالا رفته؛ پس پایین بدنه باز شدن و بالای بدنه بسته شدنه. سقف، نوک سایه‌ی بالاییه.',
        },
        {
          type: 'truefalse',
          statement: 'نوک سایه‌ی بالایی کندل، بالاترین قیمت اون بازه رو نشون می‌ده.',
          topic: 'سایه · Wick',
          answer: true,
          explanation: 'سایه‌ی بالایی تا سقف قیمت و سایه‌ی پایینی تا کف قیمت کشیده می‌شه.',
        },
        {
          type: 'chart',
          prompt: 'کندل آخر این نمودار صعودیه یا نزولی؟',
          chart: { candles: LAST_BEARISH, highlight: LAST_BEARISH.length - 1 },
          symbol: 'EUR/USD · 1H',
          options: [
            { label: 'نزولی', glyph: 'bearish' },
            { label: 'صعودی', glyph: 'bullish' },
          ],
          answer: 0,
          explanation: 'کندل آخر قرمزه و بسته شدنش پایین‌تر از باز شدنشه؛ پس نزولیه.',
        },
        {
          type: 'match',
          pairs: [
            { term: 'Open', sub: 'باز شدن', meaning: 'قیمت اول بازه' },
            { term: 'Close', sub: 'بسته شدن', meaning: 'قیمت آخر بازه' },
            { term: 'High', sub: 'سقف', meaning: 'بالاترین قیمت بازه' },
            { term: 'Low', sub: 'کف', meaning: 'پایین‌ترین قیمت بازه' },
          ],
        },
      ],
    },
    {
      id: 'cd-2',
      title: 'الگوهای تک‌کندلی',
      steps: [
        {
          type: 'learn',
          title: 'چکش (Hammer)',
          body: '**چکش** بدنه‌ی کوچیک در بالا و **سایه‌ی پایینی بلند** (حداقل دو برابر بدنه) داره. اگه **بعد از روند نزولی** ظاهر بشه، یعنی خریدارها قیمت رو از کف برگردوندن؛ نشونه‌ی احتمال **برگشت به بالا**.',
          visual: { kind: 'glyphs', items: [{ glyph: 'hammer', label: 'چکش' }] },
        },
        {
          type: 'learn',
          title: 'دوجی و ستاره‌ی دنباله‌دار',
          body: '**دوجی** بدنه‌ی خیلی کوچیکی داره؛ یعنی باز و بسته شدن تقریباً برابره و بازار **مردده**. **ستاره‌ی دنباله‌دار** برعکس چکشه: بدنه‌ی کوچیک در پایین و **سایه‌ی بالایی بلند**. بعد از روند صعودی، نشونه‌ی ضعف خریدارهاست.',
          visual: {
            kind: 'glyphs',
            items: [
              { glyph: 'doji', label: 'دوجی' },
              { glyph: 'shootingStar', label: 'ستاره‌ی دنباله‌دار' },
            ],
          },
        },
        {
          type: 'chart',
          prompt: 'کندل آخر این نمودار چه الگوییه؟',
          chart: { candles: HAMMER_AFTER_DOWNTREND, highlight: HAMMER_AFTER_DOWNTREND.length - 1 },
          symbol: 'EUR/USD · 1H',
          trend: 'down',
          options: [P.hammer, P.doji, P.shootingStar, P.bullEngulf],
          answer: 0,
          explanation: 'چکش بعد از روند نزولی میاد: بدنه‌ی کوچیک بالای کندل و سایه‌ی پایینی بلند. یعنی خریدارها قیمت رو از کف برگردوندن.',
        },
        {
          type: 'truefalse',
          statement: 'دوجی نشون می‌ده بازار بین خریدارها و فروشنده‌ها مردده.',
          topic: 'دوجی · Doji',
          answer: true,
          explanation: 'وقتی قیمت بسته شدن تقریباً با باز شدن برابره، هیچ‌کدوم از دو طرف برنده نشده.',
        },
        {
          type: 'chart',
          prompt: 'بعد از این روند صعودی، کندل آخر چه الگوییه؟',
          chart: { candles: SHOOTING_STAR_AFTER_UPTREND, highlight: SHOOTING_STAR_AFTER_UPTREND.length - 1 },
          symbol: 'BTC/USDT · 4H',
          trend: 'up',
          options: [P.shootingStar, P.hammer, P.doji, P.bearEngulf],
          answer: 0,
          explanation: 'سایه‌ی بالایی بلند و بدنه‌ی کوچیک در پایین: خریدارها قیمت رو بالا بردن ولی نتونستن نگهش دارن.',
        },
        {
          type: 'choice',
          prompt: 'الگوی چکش کی معنی‌دارتره؟',
          options: ['بعد از یه روند نزولی', 'وسط یه روند صعودی قوی', 'وقتی بازار تعطیله', 'همیشه یه معنی داره'],
          answer: 0,
          explanation: 'چکش یه الگوی برگشتیه؛ وقتی معنی داره که قبلش روند نزولی بوده باشه.',
        },
      ],
    },
    {
      id: 'cd-3',
      title: 'الگوهای دوکندلی',
      steps: [
        {
          type: 'learn',
          title: 'پوشای صعودی',
          body: 'یه کندل قرمز کوچیک و بعدش یه کندل **سبز بزرگ** که **کل بدنه‌ی** کندل قبلی رو می‌پوشونه. بعد از روند نزولی، نشونه‌ی **قدرت گرفتن خریدارهاست**.',
          visual: { kind: 'glyphs', items: [{ glyph: 'bullEngulf', label: 'پوشای صعودی' }] },
        },
        {
          type: 'learn',
          title: 'پوشای نزولی',
          body: 'برعکسش: یه کندل سبز کوچیک و بعد یه کندل **قرمز بزرگ** که بدنه‌ی قبلی رو کامل می‌پوشونه. بعد از روند صعودی، هشدار **برگشت به پایینه**.',
          visual: { kind: 'glyphs', items: [{ glyph: 'bearEngulf', label: 'پوشای نزولی' }] },
        },
        {
          type: 'chart',
          prompt: 'دو کندل آخر چه الگویی ساختن؟',
          chart: { candles: BEAR_ENGULF_AFTER_UPTREND, highlight: BEAR_ENGULF_AFTER_UPTREND.length - 1 },
          symbol: 'EUR/USD · 1H',
          trend: 'up',
          options: [P.bearEngulf, P.bullEngulf, P.hammer, P.doji],
          answer: 0,
          explanation: 'کندل قرمز بزرگ کل بدنه‌ی کندل سبز قبلی رو پوشونده؛ اونم بعد از روند صعودی. این پوشای نزولیه.',
        },
        {
          type: 'truefalse',
          statement: 'توی الگوی پوشای صعودی، کندل دوم قرمزه.',
          topic: 'پوشای صعودی',
          answer: false,
          explanation: 'توی پوشای صعودی کندل دوم سبز و بزرگه و بدنه‌ی کندل قرمز قبلی رو می‌پوشونه.',
        },
        {
          type: 'predict',
          prompt: 'بعد از این روند نزولی، یه پوشای صعودی شکل گرفته. منطقی‌ترین معامله چیه؟',
          chart: { candles: BULL_ENGULF_AFTER_DOWNTREND, ghost: true },
          symbol: 'EUR/USD · 4H',
          trend: 'down',
          answer: 'buy',
          explanation: 'پوشای صعودی بعد از روند نزولی یعنی خریدارها کنترل رو گرفتن؛ احتمال حرکت به بالا بیشتره. البته همیشه با حد ضرر!',
        },
        {
          type: 'fill',
          sentence: 'توی الگوی پوشا، بدنه‌ی کندل دوم ___ کندل اول رو کامل ___.',
          answers: ['بدنه‌ی', 'می‌پوشونه'],
          distractors: ['سایه‌ی', 'نصف می‌کنه'],
          explanation: 'اسم «پوشا» از همین میاد: بدنه‌ی کندل دوم بدنه‌ی کندل اول رو کامل می‌پوشونه.',
        },
      ],
    },
  ],
};
