/**
 * Writes the privacy policy and terms of use to the website (site/privacy, site/terms) from
 * the same text the app shows (src/content/legal.ts), so the two never drift apart, plus the
 * account deletion guide Google Play links to (site/delete-account). The English versions
 * (src/content/legal.en.ts) go to site/en/privacy, site/en/terms and site/en/delete-account.
 *
 *   npx tsx scripts/build-legal.ts
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { ACCOUNT_DELETION, LEGAL, LEGAL_UPDATED, type LegalDoc } from '../src/content/legal';
import { ACCOUNT_DELETION_EN, LEGAL_EN, LEGAL_UPDATED_EN } from '../src/content/legal.en';

const ROOT = resolve(__dirname, '..');

const escape = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

export type SiteLang = 'fa' | 'en';

type SitePage = Pick<LegalDoc, 'title' | 'intro' | 'sections'> & { id: string; english?: string[] };

/** Per language: the page chrome, and where the pages sit (`base`) and the site root is (`root`) from them. */
const UI = {
  fa: {
    dir: 'rtl',
    brand: 'چارتون',
    app: 'ورود به اپ',
    updated: `آخرین به‌روزرسانی: ${LEGAL_UPDATED}`,
    home: 'صفحه‌ی اصلی',
    courses: 'دوره‌ها',
    copyright: '© ۱۴۰۵ چارتون',
    other: { lang: 'en', label: 'English', href: (id: string) => `../en/${id}/` },
    base: '',
    root: '../',
    legal: LEGAL,
    deletion: ACCOUNT_DELETION,
  },
  en: {
    dir: 'ltr',
    brand: 'Chartoon',
    app: 'Open the app',
    updated: `Last updated: ${LEGAL_UPDATED_EN}`,
    home: 'Home',
    courses: 'Courses',
    copyright: '© 2026 Chartoon',
    other: { lang: 'fa', label: 'فارسی', href: (id: string) => `../../${id}/` },
    base: 'en/',
    root: '../../',
    legal: LEGAL_EN,
    deletion: ACCOUNT_DELETION_EN,
  },
};

export function legalPage(doc: LegalDoc, lang: SiteLang = 'fa'): string {
  const { legal, deletion } = UI[lang];
  return sitePage(doc, [legal[doc.id === 'privacy' ? 'terms' : 'privacy'], { id: deletion.id, title: deletion.title }], lang);
}

export function deletionPage(lang: SiteLang = 'fa'): string {
  const { legal, deletion } = UI[lang];
  return sitePage(deletion, [legal.privacy, legal.terms], lang);
}

function sitePage(doc: SitePage, links: { id: string; title: string }[], lang: SiteLang): string {
  const ui = UI[lang];
  const url = `https://chartoon.net/${ui.base}${doc.id}/`;
  const section = (title: string, body: string[], attrs = '') =>
    `    <section${attrs}>\n      <h2>${escape(title)}</h2>\n${body.map((p) => `      <p>${escape(p)}</p>`).join('\n')}\n    </section>`;
  const sections = [
    ...doc.sections.map((s) => section(s.title, s.body)),
    ...(doc.english && lang === 'fa' ? [section('In English', doc.english, ' lang="en" dir="ltr"')] : []),
  ].join('\n');
  return `<!doctype html>
<html lang="${lang}" dir="${ui.dir}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${escape(doc.title)} | ${ui.brand}</title>
<meta name="description" content="${escape(doc.intro)}">
<link rel="canonical" href="${url}">
<link rel="alternate" hreflang="fa" href="https://chartoon.net/${doc.id}/">
<link rel="alternate" hreflang="en" href="https://chartoon.net/en/${doc.id}/">
<link rel="alternate" hreflang="x-default" href="https://chartoon.net/${doc.id}/">
<meta name="robots" content="index, follow">
<meta name="theme-color" content="#0E1320">
<meta name="color-scheme" content="dark">
<link rel="icon" href="${ui.root}favicon.ico" sizes="48x48">
<link rel="apple-touch-icon" href="${ui.root}assets/apple-touch-icon.png">
<link rel="preload" href="${ui.root}assets/fonts/lalezar.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="${ui.root}assets/fonts/vazirmatn-400.woff2" as="font" type="font/woff2" crossorigin>
<!-- Generated by scripts/build-legal.ts from src/content/legal${lang === 'en' ? '.en' : ''}.ts; edit the text there. -->
<style>
@font-face { font-family: "Vazirmatn"; src: url("${ui.root}assets/fonts/vazirmatn-400.woff2") format("woff2"); font-weight: 400; font-display: swap; }
@font-face { font-family: "Vazirmatn"; src: url("${ui.root}assets/fonts/vazirmatn-900.woff2") format("woff2"); font-weight: 900; font-display: swap; }
@font-face { font-family: "Lalezar"; src: url("${ui.root}assets/fonts/lalezar.woff2") format("woff2"); font-weight: 400; font-display: swap; }
:root { color-scheme: dark; --bg: #0E1320; --surface: #171F31; --line: #2A3550; --line-soft: #1C2438; --text: #F1F4F9; --text2: #AEB8CC; --text3: #8792AB; --bull: #2BD47D; --sky: #5AB0FF; }
* { box-sizing: border-box; }
html { background: var(--bg); -webkit-text-size-adjust: 100%; }
body { margin: 0; background: var(--bg); color: var(--text); font: 400 1.0625rem/2 "Vazirmatn", Tahoma, system-ui, sans-serif; }
a { color: var(--sky); }
:focus-visible { outline: 3px solid var(--sky); outline-offset: 3px; border-radius: 8px; }
.wrap { width: 100%; max-width: 760px; margin-inline: auto; padding-inline: clamp(16px, 4vw, 32px); }
header { border-bottom: 1px solid var(--line-soft); }
header .wrap { display: flex; align-items: center; justify-content: space-between; gap: 16px; min-height: 64px; }
.brand { font: 400 1.8rem/1 "Lalezar", "Vazirmatn", sans-serif; color: var(--text); text-decoration: none; padding-top: 4px; }
.app { color: var(--bull); font-weight: 900; text-decoration: none; }
main { padding-block: clamp(28px, 6vw, 56px) 64px; }
h1 { margin: 0 0 6px; font: 400 clamp(2.2rem, 5vw, 3rem)/1.3 "Lalezar", "Vazirmatn", sans-serif; }
.updated { margin: 0 0 20px; color: var(--text3); font-size: 0.9rem; }
.intro { margin: 0 0 28px; font-size: 1.1rem; }
section { margin-block: 14px; padding: 18px 20px; border-radius: 18px; border: 1.5px solid var(--line); background: var(--surface); }
h2 { margin: 0 0 6px; font-size: 1.15rem; font-weight: 900; }
section p { margin: 0 0 8px; color: var(--text2); }
section p:last-child { margin-bottom: 0; }
footer { border-top: 1px solid var(--line-soft); padding-block: 28px calc(28px + env(safe-area-inset-bottom, 0px)); color: var(--text3); font-size: 0.92rem; }
footer .wrap { display: flex; flex-wrap: wrap; gap: 8px 24px; }
footer a { color: var(--text2); font-weight: 900; text-decoration: none; }
</style>
</head>
<body>
<header>
  <div class="wrap">
    <a class="brand" href="../">${ui.brand}</a>
    <a class="app" href="https://app.chartoon.net/">${ui.app}</a>
  </div>
</header>
<main class="wrap">
  <h1>${escape(doc.title)}</h1>
  <p class="updated">${escape(ui.updated)}</p>
  <p class="intro">${escape(doc.intro)}</p>
${sections}
</main>
<footer>
  <div class="wrap">
    <a href="../">${ui.home}</a>
    <a href="../courses/">${ui.courses}</a>
${links.map((l) => `    <a href="../${l.id}/">${escape(l.title)}</a>`).join('\n')}
    <a href="${ui.other.href(doc.id)}" hreflang="${ui.other.lang}" lang="${ui.other.lang}">${ui.other.label}</a>
    <span>${ui.copyright}</span>
  </div>
</footer>
</body>
</html>
`;
}

export function writeLegalPages(siteDir = join(ROOT, 'site')) {
  const written: string[] = [];
  for (const lang of ['fa', 'en'] as const) {
    const { base, legal, deletion } = UI[lang];
    const pages: [string, string][] = [...Object.values(legal).map((doc): [string, string] => [doc.id, legalPage(doc, lang)]), [deletion.id, deletionPage(lang)]];
    for (const [id, html] of pages) {
      mkdirSync(join(siteDir, base, id), { recursive: true });
      writeFileSync(join(siteDir, base, id, 'index.html'), html);
      written.push(`site/${base}${id}/index.html`);
    }
  }
  return written;
}

if (require.main === module) {
  console.log(`wrote ${writeLegalPages().join(', ')}`);
}
