/**
 * Writes the privacy policy and terms of use to the website (site/privacy, site/terms) from
 * the same text the app shows (src/content/legal.ts), so the two never drift apart, plus the
 * account deletion guide Google Play links to (site/delete-account).
 *
 *   npx tsx scripts/build-legal.ts
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { ACCOUNT_DELETION, LEGAL, LEGAL_UPDATED, type LegalDoc } from '../src/content/legal';

const ROOT = resolve(__dirname, '..');

const escape = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

type SitePage = Pick<LegalDoc, 'title' | 'intro' | 'sections'> & { id: string; english?: string[] };

const DELETION_LINK = { id: ACCOUNT_DELETION.id, title: ACCOUNT_DELETION.title };

export function legalPage(doc: LegalDoc): string {
  return sitePage(doc, [LEGAL[doc.id === 'privacy' ? 'terms' : 'privacy'], DELETION_LINK]);
}

export function deletionPage(): string {
  return sitePage(ACCOUNT_DELETION, [LEGAL.privacy, LEGAL.terms]);
}

function sitePage(doc: SitePage, links: { id: string; title: string }[]): string {
  const url = `https://chartoon.net/${doc.id}/`;
  const section = (title: string, body: string[], attrs = '') =>
    `    <section${attrs}>\n      <h2>${escape(title)}</h2>\n${body.map((p) => `      <p>${escape(p)}</p>`).join('\n')}\n    </section>`;
  const sections = [
    ...doc.sections.map((s) => section(s.title, s.body)),
    ...(doc.english ? [section('In English', doc.english, ' lang="en" dir="ltr"')] : []),
  ].join('\n');
  return `<!doctype html>
<html lang="fa" dir="rtl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${escape(doc.title)} | چارتون</title>
<meta name="description" content="${escape(doc.intro)}">
<link rel="canonical" href="${url}">
<meta name="robots" content="index, follow">
<meta name="theme-color" content="#0E1320">
<meta name="color-scheme" content="dark">
<link rel="icon" href="../favicon.ico" sizes="48x48">
<link rel="apple-touch-icon" href="../assets/apple-touch-icon.png">
<!-- Generated by scripts/build-legal.ts from src/content/legal.ts; edit the text there. -->
<style>
@font-face { font-family: "Vazirmatn"; src: url("../assets/fonts/vazirmatn-400.woff2") format("woff2"); font-weight: 400; font-display: swap; }
@font-face { font-family: "Vazirmatn"; src: url("../assets/fonts/vazirmatn-900.woff2") format("woff2"); font-weight: 900; font-display: swap; }
@font-face { font-family: "Lalezar"; src: url("../assets/fonts/lalezar.woff2") format("woff2"); font-weight: 400; font-display: swap; }
:root { color-scheme: dark; --bg: #0E1320; --surface: #171F31; --line: #2A3550; --line-soft: #1C2438; --text: #F1F4F9; --text2: #AEB8CC; --text3: #8792AB; --bull: #2BD47D; --sky: #5AB0FF; }
* { box-sizing: border-box; }
html { background: var(--bg); -webkit-text-size-adjust: 100%; }
body { margin: 0; background: var(--bg); color: var(--text); font: 400 1.0625rem/2 "Vazirmatn", Tahoma, system-ui, sans-serif; }
a { color: var(--sky); }
:focus-visible { outline: 3px solid var(--sky); outline-offset: 3px; border-radius: 8px; }
.wrap { width: 100%; max-width: 760px; margin-inline: auto; padding-inline: clamp(16px, 4vw, 32px); }
header { border-bottom: 1px solid var(--line-soft); }
header .wrap { display: flex; align-items: center; justify-content: space-between; gap: 16px; min-height: 64px; }
.brand { font: 400 1.8rem/1 "Lalezar", "Vazirmatn", sans-serif; color: var(--text); text-decoration: none; padding-top: 4px; }
.app { color: var(--bull); font-weight: 900; text-decoration: none; }
main { padding-block: clamp(28px, 6vw, 56px) 64px; }
h1 { margin: 0 0 6px; font: 400 clamp(2.2rem, 5vw, 3rem)/1.3 "Lalezar", "Vazirmatn", sans-serif; }
.updated { margin: 0 0 20px; color: var(--text3); font-size: 0.9rem; }
.intro { margin: 0 0 28px; font-size: 1.1rem; }
section { margin-block: 14px; padding: 18px 20px; border-radius: 18px; border: 1.5px solid var(--line); background: var(--surface); }
h2 { margin: 0 0 6px; font-size: 1.15rem; font-weight: 900; }
section p { margin: 0 0 8px; color: var(--text2); }
section p:last-child { margin-bottom: 0; }
footer { border-top: 1px solid var(--line-soft); padding-block: 28px calc(28px + env(safe-area-inset-bottom, 0px)); color: var(--text3); font-size: 0.92rem; }
footer .wrap { display: flex; flex-wrap: wrap; gap: 8px 24px; }
footer a { color: var(--text2); font-weight: 900; text-decoration: none; }
</style>
</head>
<body>
<header>
  <div class="wrap">
    <a class="brand" href="../">چارتون</a>
    <a class="app" href="https://app.chartoon.net/">ورود به اپ</a>
  </div>
</header>
<main class="wrap">
  <h1>${escape(doc.title)}</h1>
  <p class="updated">آخرین به‌روزرسانی: ${escape(LEGAL_UPDATED)}</p>
  <p class="intro">${escape(doc.intro)}</p>
${sections}
</main>
<footer>
  <div class="wrap">
    <a href="../">صفحه‌ی اصلی</a>
${links.map((l) => `    <a href="../${l.id}/">${escape(l.title)}</a>`).join('\n')}
    <span>© ۱۴۰۵ چارتون</span>
  </div>
</footer>
</body>
</html>
`;
}

export function writeLegalPages(siteDir = join(ROOT, 'site')) {
  const pages: [string, string][] = [...Object.values(LEGAL).map((doc): [string, string] => [doc.id, legalPage(doc)]), [ACCOUNT_DELETION.id, deletionPage()]];
  for (const [id, html] of pages) {
    mkdirSync(join(siteDir, id), { recursive: true });
    writeFileSync(join(siteDir, id, 'index.html'), html);
  }
  return pages.map(([id]) => `site/${id}/index.html`);
}

if (require.main === module) {
  console.log(`wrote ${writeLegalPages().join(', ')}`);
}
