/**
 * Regenerates src/content/i18n/en/index.ts so it imports every English overlay in that folder
 * (units/<unitId>.json and courses.json).
 *
 *   npx tsx scripts/i18n-index.ts
 */
import { existsSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const dir = resolve(__dirname, '../src/content/i18n/en');
const units = existsSync(join(dir, 'units')) ? readdirSync(join(dir, 'units')).filter((f) => f.endsWith('.json')).sort() : [];
const name = (f: string) => `u_${f.replace(/\.json$/, '').replace(/[^a-zA-Z0-9]/g, '_')}`;
const hasCourses = existsSync(join(dir, 'courses.json'));

const lines = [
  "// Generated by scripts/i18n-index.ts from the files in this folder; don't edit by hand.",
  "import type { Overlay } from '..';",
  '',
  ...(hasCourses ? ["import courses from './courses.json';"] : []),
  ...units.map((f) => `import ${name(f)} from './units/${f}';`),
  '',
  `export const EN_COURSES: Record<string, Overlay> = ${hasCourses ? 'courses' : '{}'};`,
  '',
  'export const EN_UNITS: Record<string, Overlay> = {',
  ...units.map((f) => `  '${f.replace(/\.json$/, '')}': ${name(f)},`),
  '};',
  '',
];
writeFileSync(join(dir, 'index.ts'), lines.join('\n'));
console.log(`indexed ${units.length} units${hasCourses ? ' and the course cards' : ''}`);
